# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "enscribe.dev"
# subtitle:
heading: "Hey! My name's Jason, and I go by the handle **enscribe/jktrn** on pretty much every account. I do a lot of things to find fulfillment ⁠— I enjoy cybersecurity [capture-the-flag](https://enscribe.dev/profiles/ctftime) competitions, [rhythm games](https://enscribe.dev/profiles/osu), [beautiful READMEs](https://github.com/project-sekai-ctf/sekaictf-2022), gluttony, [web development](https://github.com/jktrn/enscribe.dev/) and [Tetris](https://enscribe.dev/profiles/tetrio). You'll mainly find CTF writeups around here, which I've poured lots of love into. Thanks for stopping by! 	(・ω・)ノ"
keywords:
author: enscribe
language: en
# timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://enscribe.dev/
# permalink: 
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: articles
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

## http://momentjs.com/docs/#/displaying/format/
date_format: MMM DD, YYYY
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
ignore:

theme: cactus

## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/jktrn/enscribe.dev.git
  branch: gh-pages

alias:
  profiles/github/index.html: https://github.com/jktrn/
  profiles/youtube/index.html: https://www.youtube.com/c/jktrn?sub_confirmation=1/
  profiles/instagram/index.html: https://www.instagram.com/enscribe/
  profiles/reddit/index.html: https://www.reddit.com/user/_Enscribe/
  profiles/osu/index.html: https://osu.ppy.sh/u/enscribe/
  profiles/tetrio/index.html: https://ch.tetr.io/u/stickspin/
  profiles/steam/index.html: https://steamcommunity.com/id/enscribe/
  profiles/spotify/index.html: https://open.spotify.com/user/190ew3n8ykzdzexi8w094a79r?si=593d39b17e424aac/
  profiles/discord/index.html: https://discord.com/users/268178914982100994/
  profiles/mail/index.html: mailto:contact@enscribe.dev
  profiles/ctftime/index.html: https://ctftime.org/user/130832/
  profiles/twitter/index.html: https://twitter.com/enscry/

hide_posts:
  enable: true
  filter: hidden
  public_generators: []
  noindex: false
  
sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  rel: false
  tags: false
  categories: false